### ISSUE TITLE
Minimum Viable Product

### ISSUE THREAD

**Issue by icculus** [libsdl-org/sdl2-compat#1]
Recognizing that sdl2-compat is mostly going to start as a basic passthrough until SDL3 starts making changes, we need to do a few things to get the framework ready and then wait for those changes:

- [X] Copy documentation from sdl12-compat, update it for sdl2-compat
- [X] Copy SDL2 include directory over.
- [X] Copy SDL2 tests over.
- [x] Copy CMakeLists.txt from sdl12-compat, update it for sdl2-compat
- [x] Generate the SDL30_syms.h file, which is all passthrough stuff right now.
- [x] Do we need the Objective-C code for macOS, or was this just an SDL 1.2 thing?
- [x] Decide if we need things like x86_msvc.h
- [x] Decide if we want Watcom C things if we're dumping OS/2 for SDL3.
- [x] Copy over the loading code from sdl12-compat, update it for sdl2-compat.
- [x] Hook up the Dynamic API.
- [x] Make sure headers can be used without a configuration step (we managed to do it all with the preprocessor in sdl12-compat!)
- [x] Make a pass over the test directory to clean out things that don't make sense (`nacl` directory, build scripts, etc).
- [x] Hook up Windows, Linux, and macOS builds to GitHub Actions.
- [x] Probably other things.

**Comment by icculus** [comment]
@sezero Even if we're dropping OS/2 for SDL3, I assume you want the other Makefiles from sdl12-compat to continue on in sdl2-compat, right?

And do we want Watcom C support at all if OS/2 is gone?

**Comment by icculus** [comment]
I _think_ x86_msvc.h was put in there for the dr_mp3's use, which we don't need in sdl2-compat, because we don't have to fake a CD audio subsystem.

**Comment by sezero** [comment]
> @sezero Even if we're dropping OS/2 for SDL3, I assume you want the other Makefiles from sdl12-compat to continue on in sdl2-compat, right?

Plain makefiles make my life easier

> And do we want Watcom C support at all if OS/2 is gone?

I don't see any point in it. (Only the watcom win32 makefile might be used, but bah..)

**Comment by icculus** [comment]
> Plain makefiles make my life easier

Then they definitely stay for sdl2-compat. I'll update this today.

**Comment by sezero** [comment]
Current source tree has build issues:

- Mac: the objc source is needed because of `error_dialog()`.

- Windows: The following is needed because of SDL_CreateThread woes. Tested with mingw and msvc.
```diff
diff --git a/src/sdl3_include_wrapper.h b/src/sdl3_include_wrapper.h
index 6d78700..956b25c 100644
--- a/src/sdl3_include_wrapper.h
+++ b/src/sdl3_include_wrapper.h
@@ -913,17 +913,30 @@
 #error You need to compile against SDL >= 3.0.0 headers.
 #endif
 
-#include "SDL_syswm.h"    /* includes windows.h for _WIN32, os2.h for __OS2__ */
+#include "SDL_syswm.h"
 #include "SDL_vulkan.h"
 
 /* Missing SDL_thread.h stuff (see above): */
 #if defined(_WIN32)
+#ifndef WIN32_LEAN_AND_MEAN
+#define WIN32_LEAN_AND_MEAN 1
+#endif
+#include <windows.h>
 typedef struct SDL_Thread SDL_Thread;
+typedef unsigned long SDL_threadID;
+typedef enum {
+    SDL_THREAD_PRIORITY_LOW,
+    SDL_THREAD_PRIORITY_NORMAL,
+    SDL_THREAD_PRIORITY_HIGH,
+    SDL_THREAD_PRIORITY_TIME_CRITICAL
+} SDL_ThreadPriority;
+typedef unsigned int SDL_TLSID;
 typedef int (SDLCALL *SDL_ThreadFunction) (void*);
 typedef UINT_PTR (__cdecl *pfnSDL_CurrentBeginThread)
                    (void*, unsigned, unsigned (__stdcall *func)(void*), void*, unsigned, unsigned*);
 typedef void (__cdecl *pfnSDL_CurrentEndThread) (unsigned);
 /* the following macros from Win32 SDK headers are harmful here: */
+#undef CreateWindow
 #undef CreateThread
 #undef CreateSemaphore
 #undef CreateMutex
```

Do I have push permissions?

(P.S.: the library names should be updated after https://github.com/libsdl-org/SDL/issues/5626 solidifies.)

**Comment by icculus** [comment]
> Do I have push permissions?

The whole a-team should; let me know if it doesn't work and I'll send an invite directly.

Otherwise, push anything you think is appropriate!

**Comment by icculus** [comment]
Okay, I added the Objective-C code back in and took a first shot at migrating the Makefiles (but you'll have to check if they actually work...the version numbers are probably wrong if nothing else).

I haven't pushed the patch you posted; go ahead and try that yourself to make sure you have access!

**Comment by sezero** [comment]
>   Decide if we want Watcom C things if we're dumping OS/2 for SDL3.

There is only one place, the Win32 init code, in sdl2_compat.c where there
is a watcom ifdef, and it doesn't hurt to keep it as is.

**Comment by sezero** [comment]
> I _think_ x86_msvc.h was put in there for the dr_mp3's use

If we ever do 64 bit arithmetic in 32 bit for some compatibility code, then we'll need it again.

**Comment by sezero** [comment]
> > I _think_ x86_msvc.h was put in there for the dr_mp3's use
> 
> If we ever do 64 bit arithmetic in 32 bit for some compatibility code, then we'll need it again.

... And we hit it:
```
sdl2_compat.obj : error LNK2019: unresolved external symbol __ftol2_sse referenced in function _SDL_CalculateGammaRamp_REAL
SDL2.dll : fatal error LNK1120: 1 unresolved externals
```

**Comment by sezero** [comment]
I just added x86_msvc.h as of commit 2ba8d7ba52a9d0e3902b848cc1ea69fec0916738 - x86 links fine now with msvc.

**Comment by icculus** [comment]
Dynamic API went in today, and enough of the compat layer is working that I was able to run testsprite2 on SDL3, both with LD_LIBRARY_PATH and SDL_DYNAMIC_API, which is pretty awesome.

I still have to catch up on other API changes, but we're almost at the point where we just have to keep up with ongoing SDL3 development!

**Comment by slouken** [comment]
Woo! :)

**Comment by sezero** [comment]
Just tested SDL2 build of [quakespasm](https://sourceforge.net/projects/quakespasm/) on i686 linux and it seems to smoothly talks to SDL3 through sdl2-compat, both with LD_LIBRARY_PATH and SDL_DYNAMIC_API.

**Comment by sezero** [comment]
Also tested the crazy thing of chaining sdl12-compat with sdl2-compat by running the SDL-1.2 build of quakespasm, uhexen2 (both opengl and software renderers) and hhexen: Seems to work:
```
INFO: sdl2-compat 2.90.0, built on Nov 30 2022 at 22:45:15, talking to SDL3 3.0.0
INFO: This app appears to be named 'hexen2'
INFO: sdl12-compat 1.2.61, built on Nov 29 2022 at 23:29:38, talking to SDL2 2.90.0
INFO: This app appears to be named 'hexen2'
```

**Comment by icculus** [comment]
We all have to commit to dying of old age before SDL 12.0 ships, though, so worrying about what we named sdl12-compat will be someone else's problem.  :)

**Comment by icculus** [comment]
> Make sure headers can be used without a configuration step (we managed to do it all with the preprocessor in sdl12-compat!)

We haven't done this yet. sdl12-compat [fakes it](https://github.com/libsdl-org/sdl12-compat/blob/main/include/SDL/SDL_config.h), and while SDL2 is a more complex library, it would be nice if it could do the same.

Right now, building against sdl2-compat's headers will get you platform-specific SDL_config_*.h files for lots of common platforms and SDL_config_minimal.h for everything else...and honestly, maybe that's good enough. SDL2-based apps have been generally able to compile with the unconfigured SDL headers for a long time, so maybe if an app depends on this, we should consider it their bug?

**Comment by icculus** [comment]
> so maybe if an app depends on this, we should consider it their bug?

I am certain this is going to trigger a bug report from Debian or Fedora at some point, for an open source game that relies on it to define `HAVE_STDIO_H` or whatever, but for now I'm comfortable with the current state of the headers and we'll deal with those bugs when they arrive.

**Comment by icculus** [comment]
And therefore this bug can close!
