### ISSUE TITLE
video_getNumDisplayModes test fails under dummy video driver

### ISSUE THREAD

**Issue by smcv** [libsdl-org/sdl2-compat#101]
To reproduce:

* Debian 12 in a qemu/kvm virtual machine (running GNOME 43 in Wayland mode, if that matters)
* SDL 3 libsdl-org/SDL@4db2b968 in `~/src/SDL3`, configured with `cmake -S . -B _build -DSDL_TESTS=ON` and compiled
* SDL 2 libsdl-org/SDL@9772d051 in `~/src/SDL2`, configured with `cmake -S . -B _build -DSDL_TESTS=ON` and compiled
* sdl2-compat 52d96367 in `~/src/sdl2-compat`, configured with `cmake -S . -B _build -DSDL3_INCLUDE_DIRS=$HOME/src/SDL3/include -DSDL2COMPAT_TESTS=ON` and compiled
* `export SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy SDL_VIDEO_DRIVER=dummy SDL_AUDIO_DRIVER=dummy`
* `cd ~/src/SDL3/_build/test; ./testautomation` (all succeeds)
* `cd ~/src/SDL2/_build/test; ./testautomation` (there are some test failures which are out-of-scope for this bug report, but `video_getNumDisplayModes` succeeds)
* `cd ~/src/sdl2-compat/_build; LD_LIBRARY_PATH=$HOME/src/SDL3/_build ./testautomation`
* `cd ~/src/sdl2-compat/_build; LD_LIBRARY_PATH=$HOME/src/SDL3/_build ./testautomation --filter video_getNumDisplayModes`

Expected result: sdl2-compat test suite passes

Actual result:

```
INFO:  09/28/23 11:08:57: ----- Test Case 21.6: 'video_getNumDisplayModes' started
INFO:  09/28/23 11:08:57: Test Description: 'Use SDL_GetNumDisplayModes function to get number of display modes'
INFO:  09/28/23 11:08:57: Test Iteration 1: execKey 13259322882708337379
INFO:  09/28/23 11:08:57: Assert 'Call to SDL_GetNumVideoDisplays()': Passed
INFO:  09/28/23 11:08:57: Assert 'Call to SDL_GetNumDisplayModes(0)': Passed
ERROR: 09/28/23 11:08:57: Assert 'Validate returned value from function; expected: >=1; got: 0': Failed
ERROR: 09/28/23 11:08:57: Assert Summary: Total=3 Passed=2 Failed=1
INFO:  09/28/23 11:08:57: Total Test runtime: 0.0 sec
ERROR: 09/28/23 11:08:57: >>> Test 'video_getNumDisplayModes': Failed
```

**Comment by smcv** [comment]
`video_getClosestDisplayModeCurrentResolution` and `video_getWindowDisplayMode` are also failing, but based on their names, I assume it isn't really worth investigating those until this one is fixed.

`video_createWindowVariousFlags` is also failing, but it's failing in "real" SDL2 as well, so I'll report that as a SDL2 issue instead.

**Comment by Kontrabant** [comment]
On SDL3, the dummy driver doesn't expose any exclusive fullscreen modes, which is acceptable behavior in SDL3, but causes issues in SDL2, which expects at least one video mode to be returned, as SDL2 backends returned the desktop mode as a fullscreen mode.

The quick fix is to simply expose a fake fullscreen mode via the dummy driver, but if a future 'real' SDL3 backend doesn't expose any exclusive fullscreen modes, applications run against SDL2-compat might run into problems. This probably isn't worth worrying about right now unless this hypothetical backend becomes a reality, though.

For now, let's just fix up the SDL3 dummy driver for the sdl2-compat tests, and if real applications have real problems, further measures can be taken.

**Comment by Kontrabant** [comment]
Hmm, looking further into this, there are already several SDL3 backends that don't expose anything but the desktop mode. I'll looking into handling this at the sdl2-compat layer instead.

**Comment by Kontrabant** [comment]
All of the automated video tests should be passing with X11, Wayland and the dummy driver now.
