### ISSUE TITLE
should we have CMAKE_SKIP_RPATH TRUE ?

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/sdl2-compat#13]
just renamed the issue with madebr comment:

**Comment by madebr** [comment]
The tests are linked against the correct library, but the tests inside the build directory don't have their run path set:
https://github.com/libsdl-org/sdl2-compat/blob/9e1afdfa13485ae1a650672f7a2c2ffa2a1fa2b4/CMakeLists.txt#L97

I think that line should not be there.
CMake will remove the run path when installing the files.

**Comment by 1bsyl** [comment]
yes, sorry, obviously wrong reporting :) sdl2-compat builds the libSDL2 ... I just need to set the correct LD_LIBRARY_PATH

I leave this opened for your remark about RPATH, @madebr, if this needs to be solved.

**Comment by madebr** [comment]
`set(CMAKE_SKIP_RPATH TRUE)` has been removed in https://github.com/libsdl-org/sdl2-compat/commit/cabf98a94f444f969132897441eb3ad0bbf82cbd.
