### ISSUE TITLE
flicker / issue rendering ? 

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/sdl2-compat#17]
./testgeometry : triangle disappears when moving / click with the mouse. it should rotate the triangle instead.
./testsprite2 flickers (not sure ?)

not sure why:  mouse coords ? maybe missing sensor/ joysticks locks ? )

**Comment by sezero** [comment]
Mouse coords became floats in SDL3, that should be the reason. Still a TODO:
https://github.com/libsdl-org/sdl2-compat/blob/main/src/sdl2_compat.c#L1357-L1358

**Comment by 1bsyl** [comment]
ok thanks ! 
maybe the issue, i haven't investigated yet

**Comment by 1bsyl** [comment]
maybe, does ./testgeometry compile ? if you run it ?
