### ISSUE TITLE
macOS: rendering textures is busted...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/sdl2-compat#196]
This is testsprite2, using the latest sdl2-compat and SDL3 on macOS:

<img width="647" alt="image" src="https://github.com/user-attachments/assets/d64dddb3-87de-40e1-9870-2791a80a3fd2">

Normal SDL2 testsprite2 works fine, as does SDL3's testsprite.

**Comment by icculus** [comment]
This is SDL3 revision 40f9fd854fd56bbf1ed117879e1f6654276c8ec7 (which is not the culprit, just where I am in bisecting this)...

<img width="647" alt="image" src="https://github.com/user-attachments/assets/04a8e893-b6ee-4dac-b58f-1cfa2fd93e65">

**Comment by icculus** [comment]
I couldn't manage to bisect it, but it works with all renderer backends if I convert icon.bmp from 8-bit indexed color to RGB565, so I'm assuming this was the blit-with-no-palette change in SDL3.

It's not a Metal-specific thing, it didn't work on OpenGL or Software rendering, either. Both looked like this, unlike Metal's blank output:

<img width="647" alt="image" src="https://github.com/user-attachments/assets/3e01a2eb-7078-4a0a-8918-1e1016aa8902">

This is likely not Mac-specific after all, but I haven't checked.

**Comment by slouken** [comment]
Fixed, thanks!

**Comment by sezero** [comment]
BTW: is SDL_image OK?

**Comment by slouken** [comment]
Yep!
