### ISSUE TITLE
Supertux: Can't play Treasure Moutain

### ISSUE THREAD

**Issue by chadchoi** [libsdl-org/sdl2-compat#234]
The message box said:

SuperTux has encountered an unrecoverable error!

Clicking into the Details button show a bunch of `<no symbol available>`.

SuperTux will crash after the button OK is clicked.

**Comment by Kontrabant** [comment]
Please report this to the Supertux project to confirm that the problem is SDL related. If it is, a backtrace or a simple repro case is required to locate and fix whatever the problem is.

**Comment by chadchoi** [comment]
Everything is fine with the real SDL2. As I know, the Supertux project doesn't support sdl2-compat. How can I report this to them?

**Comment by Kontrabant** [comment]
Their bug tracker https://github.com/SuperTux/supertux/issues

**Comment by chadchoi** [comment]
This is not theirs issue. This is your issue.

**Comment by chadchoi** [comment]
I'm not a programmer but I think I can understand the error message. There are SDL2 functions you have not yet implemented, hence `<no symbol available>`.

**Comment by Kontrabant** [comment]
No, that means the executable and/or libraries were built without debug info. If it only crashes on sdl2-compat and not real SDL2, this can be reopened, but a proper backtrace is still needed to know exactly what the problem is.

**Comment by chadchoi** [comment]
Can you try to reproduce this yourself? I know I should provide more information but I don't even know what a backtrace is. I'm on Windows and I'm using SuperTux Nightly 64 bit MSI downloaded from their website. How I replace the real SDL2 with sdl2-compat I have already mentioned.

**Comment by chadchoi** [comment]
And I don't build sdl2-compat myself, too. I use another Github user's build:

https://github.com/mmozeiko/build-sdl3/releases

**Comment by chadchoi** [comment]
Update: I'm sorry. I seem I forgot to submit the comment. I downloaded the x64 SDL3 build by mmozeiko, extracted it and added it to PATH. I renamed the SDL2.dll shipped with SuperTux to SDL2.dll.bak and SuperTux will pick up the SDL2.dll in PATH which is sdl2-compat.

**Comment by Kontrabant** [comment]
Had a moment to look into this, and the nightly version crashes with this custom level no matter what platform or version of SDL is used, while the stable release works with both SDL2 and sdl2-compat.

Backtrace:
#0  0x00007ffff7f7fce8 in sq_stackinfos () from /tmp/.mount_SuperTLdLv6R/usr/lib/libsimplesquirrel.so
#1  0x00007ffff7f9e5ce in sqstd_printcallstack () from /tmp/.mount_SuperTLdLv6R/usr/lib/libsimplesquirrel.so
#2  0x0000555555763948 in SquirrelEnvironment::run_script(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .cold] ()
#3  0x000055555591bc61 in worldmap::WorldMapSector::setup() ()
#4  0x0000555555911898 in worldmap::WorldMap::set_sector(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) ()
#5  0x0000555555924632 in worldmap::WorldMapState::load_state() ()
#6  0x00005555559110c2 in worldmap::WorldMap::setup() ()
#7  0x000055555589705b in ScreenManager::handle_screen_switch() ()
#8  0x00005555558973a3 in ScreenManager::loop_iter() ()
#9  0x0000555555897530 in ScreenManager::run() ()
#10 0x000055555584d62d in Main::launch_game(CommandLineArguments const&) ()
#11 0x000055555584ebbb in Main::run(int, char**) ()
#12 0x0000555555776c2e in main ()

The nightly version is crashing somewhere in the Squirrel script interpreter, not SDL. This should be reported to the SuperTux bug tracker.
