### ISSUE TITLE
Android run fails on dynamic load of libSDL3.so

### ISSUE THREAD

**Issue by capocasa** [libsdl-org/sdl2-compat#236]
Built an app based on the default android-project in SDL main branch (SDL 3.0). Added sdl2-compat to the CMakeLists.txt.

App builds fine but fails with this output:

```
11-27 23:09:06.639 12534 12534 F SDL2COMPAT: Failed loading SDL3 library.
```

This seems to be the case whether or not SDL3 is loaded via the `getLibraries()` call in java.

Is Android currently supported for the SDL2 compatibility layer?

**Comment by slouken** [comment]
No, sdl2-compat isn't supported on Android.

**Comment by capocasa** [comment]
Thanks for letting me know!

**Comment by slouken** [comment]
You're welcome!
