### ISSUE TITLE
procs returning (and possibly accepting) SDL_XxxID types

### ISSUE THREAD

**Issue by sezero** [libsdl-org/sdl2-compat#26]
Some procs returning (and possibly accepting) `SDL_XxxxID` type seem to
have wrong signatures, e.g. `SDL_SensorID` instead of `SDL2_SensorID`,
i.e. signed vs unsigned. Do we want to fix them? (Noticed by a warning
from g++ 3.4)
```
sdl2_compat.c: In function `SDL2_JoystickID SDL_JoystickGetDeviceInstanceID_REAL(int)':
sdl2_compat.c:3712: warning: converting of negative value `-0x000000001' to `unsigned int'
sdl2_compat.c: In function `SDL2_SensorID SDL_SensorGetDeviceInstanceID_REAL(int)':
sdl2_compat.c:3828: warning: converting of negative value `-0x000000001' to `unsigned int'
```

**Comment by slouken** [comment]
Yeah, this looks wrong, and I think that's a good warning. In SDL3, 0 is an invalid instance ID, where in SDL2, -1 is an invalid instance ID.

**Comment by sezero** [comment]
Pushed https://github.com/libsdl-org/sdl2-compat/commit/5f8ae97b2d773837d2ee5558a811ac5272e8f5e9 and https://github.com/libsdl-org/sdl2-compat/commit/aefeebcc416169c36fb16dad080f0c0e658ff8f9 - please make sure that they are OK and nothing is broken.
