### ISSUE TITLE
Catch up with initial API changes

### ISSUE THREAD

**Issue by icculus** [libsdl-org/sdl2-compat#3]
Now we're at the point where I can start filling these in, but there's a little bit of catch-up to do with API changes that have already landed in SDL3.

I filled in the removed SDL_RWFromFP as a start, but there are several others already to catch up on.

After this catches up, this bug can close, and then we can just sort of keep this in sync as we go.

**Comment by sezero** [comment]
Pushed https://github.com/libsdl-org/sdl2-compat/commit/842c8c9b28d7d5345cf684b5972351a2d5ca6aae to implement SDL_GetTicks and SDL_GetTicks64 after SDL3
timer changes. @slouken, @icculus: Please check.

**Comment by sezero** [comment]
The library is broken at present:

- The SDL_Event structures have changed timestamp from 32 bits to 64 bits.

- `GameControllerGetSensorDataWithTimestamp` and `SensorGetDataWithTimestamp`
  are removed from SDL3: they are still in sdl3 syms.h as passthrough and
  load attempts will fail only because I didn't want builds to fail: Even
  if you add stubs for them the library will segfault miserably, because
  the event changes aren't handled properly yet.

**Comment by icculus** [comment]
Yeah, there's a lot to do...I'm going to catch up sdl2-compat early this week.

**Comment by icculus** [comment]
Okay, we're back in business again. I spent way more time with this than I expected, but here's what I decided for SDL_Event handling:

- sdl12-compat implements its own event queue, just pulling in events from SDL2 when pumping, but the SDL2 queue is way more complex (locking, allocation, the poll sentinel, etc), so I ended up abandoning this.
- Copying the SDL2 code verbatim into sdl2-compat was an option, but it's a lot of code, and you still have SDL3 doing all that same work anyhow, so I ended up abandoning this, too.
- What I ended up doing instead: we use the SDL3 event queue! Whenever we need an SDL2 event (SDL_PollEvent, SDL_PushEvent, etc), we convert at that point, which right now means just adjusting for the timestamp field. We always run an SDL3 event filter (which doesn't do anything atm if there aren't any SDL2 event filters or event watchers to run)...nothing else has changed yet, but when, for example, SDL_WINDOWEVENT gets split into multiple toplevel events, this filter will insert an equivalent SDL3 event into the queue with the appropriate type, and then _leave the SDL3 event alone_. When the original event gets to the app, the SDL3 version will just have an event type it can't recognize, which might have been something added in a later SDL2 for all it knows, or perhaps an user-registered event, and ignore it.

Maybe this blows up in fun ways, but for now, we're back to a working state. I've also fixed up the other things that changed (SDL_assert data type names, joystick balls, sensor timestamps). There are probably other things that have changed since that I still need to fix up, but we aren't totally blocked now.

**Comment by icculus** [comment]
> Mouse coords becoming floats in SDL3 needs dealing with.

This should be resolved now with your PR (thanks!).

I _think_ we're caught up now in general (but there are still some bugs to work out with device indices vs instance ids, etc), and we should probably close this and start opening separate issues for future things, as more things will be changing and it'll be good to see clearly what work is pending.
