### ISSUE TITLE
What to do with SDLtest?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/sdl2-compat#4]
Do we promise API/ABI compat on SDLTest?

Right now most of the test programs in sdl2-compat won't build because they need this lib, and I'm thinking we should probably just copy its sources out of SDL2, and SDL3 shouldn't worry about maintaining compat, but I'm not sure if we consider this a public library at all, or if its installation is purely coincidental.

(and if we consider it a public library, we need to track API changes and provide for this in sdl2-compat.)

**Comment by slouken** [comment]
It is a public library, but it’s always built statically and there are no guarantees about API or ABI.

I think it makes sense for sdl2-compat to just include a copy of it and build and distribute it along with the shim library.
