### ISSUE TITLE
Generate sdl3_syms.h ? 

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/sdl2-compat#54]
maybe we should use gendynapi.pl to generate:
sdl3_include_wrapper.h
sdl3_syms.h

like generate an api_sdl2.json, generate a api_sdl3.json, 
and output and process the diff into sdl3 files ?

**Comment by sezero** [comment]
Complicated. If we do that, we have to invent a new SDL3_SYM_UNUSED, because we only add the syms we do use in there.

**Comment by sezero** [comment]
> Complicated. If we do that, we have to invent a new SDL3_SYM_UNUSED, because we only add the syms we do use in there.

I meant that only for sdl3_syms.h

**Comment by 1bsyl** [comment]
yes, true ...
