### ISSUE TITLE
struct SDL_hid_device_info incompatibility

### ISSUE THREAD

**Issue by sezero** [libsdl-org/sdl2-compat#76]
We have a new SDL2 incompatibility: `struct SDL_hid_device_info` has
              got inserted a new `bus_type` member. The structure is public, at it
              is a parameter to `SDL_hid_enumerate` and `SDL_hid_free_enumeration`.
              sdl2-compat still wrongly does passthrough for those: Needs taking
              care of.

_Originally posted by @sezero in https://github.com/libsdl-org/SDL/issues/7736#issuecomment-1565702086_
            

CC: @slouken

**Comment by slouken** [comment]
Good point. I can move the bus_type member to the end, to preserve compatibility.

**Comment by sezero** [comment]
> Good point. I can move the bus_type member to the end, to preserve compatibility.

Yes, that'd be a solution.

**Comment by slouken** [comment]
Actually, the structure looks nicer the way it is. @icculus, what do you think about preferring SDL 3.0 aesthetics over sdl2-compat passthrough ability?

**Comment by icculus** [comment]
It's not a big surface area, we can manage it in sdl2-compat.

**Comment by icculus** [comment]
Fixed in 1f3483131fdcf2302f0d4e747dcea57390f38d79.
