### ISSUE TITLE
`sdl2-config --cflags` vs header install path

### ISSUE THREAD

**Issue by icculus** [libsdl-org/sdl2-compat#85]
`sdl2-config --cflags` reports, among other things, this include path...

```
-I/usr/local/include/SDL
```

...but it installs its headers in /usr/local/include/SDL2

One of these two is incorrect.

**Comment by sezero** [comment]
`sdl2-config` is wrong. The following fixes it:
```diff
diff --git a/sdl2-config.in b/sdl2-config.in
index e564bf3..d21b1b2 100755
--- a/sdl2-config.in
+++ b/sdl2-config.in
@@ -50,7 +50,7 @@ while test $# -gt 0; do
       echo @PROJECT_VERSION@
       ;;
     --cflags)
-      echo -I${includedir}/SDL @SDL_CFLAGS@
+      echo -I${includedir}/SDL2 @SDL_CFLAGS@
       ;;
 @ENABLE_SHARED_TRUE@    --libs)
 @ENABLE_SHARED_TRUE@      echo -L${libdir} @SDL_RLD_FLAGS@ @SDL_LIBS@
diff --git a/sdl2_compat.pc.in b/sdl2_compat.pc.in
index 3518708..2f0f9c0 100644
--- a/sdl2_compat.pc.in
+++ b/sdl2_compat.pc.in
@@ -8,7 +8,7 @@ includedir=@CMAKE_INSTALL_FULL_INCLUDEDIR@
 Name: sdl2_compat
 Description: An SDL2 compatibility layer that uses SDL3 behind the scenes.
 Version: @PROJECT_VERSION@
-Provides: sdl = @PROJECT_VERSION@
+Provides: sdl2 = @PROJECT_VERSION@
 Libs: -L${libdir} @SDL_RLD_FLAGS@ @SDL_LIBS@
 @ENABLE_STATIC_TRUE@Libs.private: -L${libdir} @SDL_LIBS@ @SDL_STATIC_LIBS@
 Cflags: -I${includedir}/SDL2 @SDL_CFLAGS@
```

Note the changes to pkg-config file as well: should be a copy+paste error from sdl12-compat.
However: upon running pkg-config, I get an error:
```bash
$ PKG_CONFIG_PATH=~/x2/lib/pkgconfig pkg-config --cflags sdl2
Package sdl2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `sdl2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sdl2' found
```

Same thing happens with sdl12-compat. Both install the compat pc files, i.e.
sdl12_compat.pc and sdl2_compat.pc, not sdl.pc or sdl2.pc. Is this supposed
to happen? How is it supposed to work?

**Comment by sezero** [comment]
> `sdl2-config` is wrong. The following fixes it:
> 
> ```diff
> diff --git a/sdl2-config.in b/sdl2-config.in
> index e564bf3..d21b1b2 100755
> --- a/sdl2-config.in
> +++ b/sdl2-config.in
> @@ -50,7 +50,7 @@ while test $# -gt 0; do
>        echo @PROJECT_VERSION@
>        ;;
>      --cflags)
> -      echo -I${includedir}/SDL @SDL_CFLAGS@
> +      echo -I${includedir}/SDL2 @SDL_CFLAGS@
>        ;;
>  @ENABLE_SHARED_TRUE@    --libs)
>  @ENABLE_SHARED_TRUE@      echo -L${libdir} @SDL_RLD_FLAGS@ @SDL_LIBS@
> diff --git a/sdl2_compat.pc.in b/sdl2_compat.pc.in
> index 3518708..2f0f9c0 100644
> --- a/sdl2_compat.pc.in
> +++ b/sdl2_compat.pc.in
> @@ -8,7 +8,7 @@ includedir=@CMAKE_INSTALL_FULL_INCLUDEDIR@
>  Name: sdl2_compat
>  Description: An SDL2 compatibility layer that uses SDL3 behind the scenes.
>  Version: @PROJECT_VERSION@
> -Provides: sdl = @PROJECT_VERSION@
> +Provides: sdl2 = @PROJECT_VERSION@
>  Libs: -L${libdir} @SDL_RLD_FLAGS@ @SDL_LIBS@
>  @ENABLE_STATIC_TRUE@Libs.private: -L${libdir} @SDL_LIBS@ @SDL_STATIC_LIBS@
>  Cflags: -I${includedir}/SDL2 @SDL_CFLAGS@
> ```
> 
>  upon running pkg-config, I get an error:
> 
> ```shell
> $ PKG_CONFIG_PATH=~/x2/lib/pkgconfig pkg-config --cflags sdl2
> Package sdl2 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `sdl2.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'sdl2' found
> ```
> 
> Same thing happens with sdl12-compat. Both install the compat pc files, i.e. sdl12_compat.pc and sdl2_compat.pc, not sdl.pc or sdl2.pc. Is this supposed to happen? How is it supposed to work?

Looks like it relies on the `Provides` field support in `pkgconf` (which distros seem to prefer these days) not something supported by traditional pkg-config.

**Comment by traversaro** [comment]
> Looks like it relies on the `Provides` field support in `pkgconf` (which distros seem to prefer these days) not something supported by traditional pkg-config.

Crossref related issue on sdl12-compat: https://github.com/libsdl-org/sdl12-compat/issues/162 .
