### ISSUE TITLE
Compatbilty with SDL12-compat?

### ISSUE THREAD

**Issue by Bitwolfies** [libsdl-org/sdl2-compat#99]
As far as I know, SDL12 requires SDL 2 to be installed, as youd expect if its forwarding all its calls into it. Does that mean that with both installed it will forward to SDL2 compat which then forwards to SDL3? Is that a supported usecase? Or will SDL 12 eventually be rewritten to use SDL3?

Just curious, thank you!

**Comment by slouken** [comment]
Questions are best asked on the discussion group:
https://discourse.libsdl.org/c/sdl-development/6

The quick answer is yes, sdl12-compat -> sdl2-compat -> SDL3 is a supported use case.
